language: node_js
node_js: '12'
services:
- docker
script:
- yarn build
- scripts/release.sh
env:
  global:
    secure: XeKJAQ0PifK+G7/uyOGZ6DTG4PKsH0wMtOEbHhRx8w56EHPlRaDmVUslqBnZOFp5XOo+Q4fRNtazKEo/t3+o6f9Si/OrIikzbKeOytjWuxP4IWQrXFXT32ZBmtG80COdF3VmAG+VrNA31wj34JwAE9CTvMCXnWDT4/SOekmbd4I8cmgoZRABF6rGiStPwoMRyyZmljAbd7jQdbxuP+/7FFxZRlKtI7hJD04v2ZAc+VdNOotebZ+N9/QHAtV45CD8UBepO0RudB/7o3iBOB7S/i2GRBW12pXvDCKrbyxWf/FRmnpPQJXZ50R+gDXt1azDcSHcs8PsYr8lqV83Bo8vTCEfbijmRQ5rar24FQEBqsRjWGGVekZKosFASvO8SOZSVmd1Wr2h5i04tagTF99xdWqOP1v40ro9LAllHN7YEa5BorHd+lP2ZMHxnVJHAUVVT7wrQ69rfPINUon0R6IN9TT7o8HrK5uuc83UmsOV36U1ZAA6fQiPnZ/tIMkZ2Lg7gcgj5Zlj1Bc1Oy1P6V1V7J5yHOdk6AIWR7Fs960xrOBqzQ1ZUgf7O98/mVF/fjOPcp3DSC2CkRLRb6fs3KdjaZbSeq3jj2mKYSju/9XOY8qfveFUx4rqo5j/ma0PQ0OJ8q2hyXUxtw2lgD6VNnPa81gJAU/vtGeLBcWg8mOedRI=
