language: node_js
node_js: "12"
services:
- docker
script:
- yarn build
- "./release.sh"
env:
  global:
    secure: BWnSgzwhC+fJxR+DSq9fVl1N5bd4gJRF14dF498megbKUmqatM7reP8czX1IEPvmcpH6d20hU0LfEqCcQXFXyQRbIbSWgqBQ5juiWC39aTGLs/cFDeow6JGVXOpnn7fp1BDs78x1NhI+6X2dMK0VIr4xmdC6ktiiLGPRQLvQ745ob7EV5g+IqwhaJY7pAS0aNQe0N/UMCS5aN0ifSgumWPWWJMlOL2GiV0pIFbZm1ItJ3ytlVkd1OA786BHur08R3YRl98gKVSLxe8QZ9ofa4gIBojb39wci8xQkxMxSrPhfLYOvZt2VuUjEYb+t/XG9hFFdNyyj2bnvemk9IgFk7ekM4Z5IQ4t50h+xMRQwH4YrrWX/OBcFT1FsD8/NKtatP/7ou/bSwxPRnSimcU8b86Q3b40TfTnojJcrrwTy5lVB5BHixSkJx95+cq0oWW6JeN99KVffUE9d4he8brCqKesVLUy0/ZGw0T1FQoD4OIzEx8c7S3i0QnEvuDuM70lWQTlctL5sDOTIddZ3JUp+4QxwoapL5TR2xgi0TNhFIdx0JjuSU9FHBGHrXe2B2JyKf9Nq0T785hPo9dbeDdNMpH5zPwSLzSJhZhmWnaMImJ5n7t3zK6KMg6q4OGyzYw6w1ZwCP9p7YYiaCdzp2Q7KQ9DybSZjP61EwiO+M/Fkajw=
