name: Build WASM

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v7
        with:
            version: 2.0.15

      - name: Install dependencies
        run: scripts/install_deps.sh

      - name: Build WASM
        run: scripts/build_clingo.sh

      - name: Commit WASM
        run: |
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            git config --global user.name 'GitHub Action'
            git config --global user.email 'domoritz@users.noreply.github.com'
            git add clingo.wasm clingo.js
            git commit -m "[CI] Automated build of WASM files."
            git push
          else
            echo "No changes detected in WASM file."
          fi
