name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Node dependencies
        run: yarn --frozen-lockfile
      - name: Build JS
        run: yarn build
      - name: Test
        run: yarn test
