name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install Node dependencies
        run: npm ci
      - name: Build JS
        run: npm run build
      - name: Test
        run: npm test
